version: '2'

services:
  web:
    image: nginx:mainline-alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - vips-network
  php:
    build: .
    volumes:
      - ./html:/var/www/html
      - ./vendor:/var/www/vendor
    networks:
      - vips-network

networks:
  vips-network:
    driver: bridge
